name: Create Archive
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: "9.1.1"
    - name: pnpm install
      run: |
        pnpm store path
        pnpm install
        pnpm install codemirror echarts  highlight.js react-codemirror2 react-github-calendar 
    - name: Archive Release source
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: '7z'
        filename: 'release.7z'
        exclusions: node_modules
    - name: Archive Release packages
      uses: edgarrc/action-7z@v1
      with:
        args: 7z a -m0=lzma2 -mx t1.7z 'D:\.pnpm-store'
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release.7z
          t1.7z
        tag_name: ${{ github.event.inputs.tags }}
