name: Create Archive
on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags to create build'
jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: "9.1.1"
    - name: pnpm install
      run: |
        pnpm install
        pnpm install codemirror echarts  highlight.js react-codemirror2 react-github-calendar
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: '7z'
        filename: 'release.7z'
    - name: create release and upload assets
      uses: softprops/action-gh-release@v2
      with:
        files: release.7z
        tag_name: ${{ github.event.inputs.tags }}
